### PR TITLE
Next version will be 0.0.59

### PR DESCRIPTION
**Pull request by mhdirkse**

### CODE REVIEW

**Comment by mhdirkse** [comment]
Willen jullie deze mergen ongeacht de testresultaten? Dit gaat ervoor zorgen dat ik niet nogmaals 0.0.58 ga publiceren als het weer tijd is om de release procedure te doen. Voor de functionaliteit is er verder geen effect.

**Comment by philipsens** [comment]
Kan het uitvoeren van `npm version patch` niet gewoon onderdeel maken van de "release procedure"

**Review by jacodg — APPROVED** [review]

**Comment by Matthbo** [comment]
@mhdirkse @jacodg Why was Sergi's comment ignored?
I also made a comment for the previous version bump pr which got ignored too

**Comment by jacodg** [comment]
I don't know what npm version patch will do. To me it felt like a general remark on the release process, not specific to this version which we wanted to get done. Maybe we can have a meeting on your suggestions about our release process? We are probably going to change it anyways (not using WebJars anymore)

**Comment by philipsens** [comment]
> I don't know what npm version patch will do. To me it felt like a general remark on the release process, not specific to this version which we wanted to get done. Maybe we can have a meeting on your suggestions about our release process? We are probably going to change it anyways (not using WebJars anymore)

`npm version patch` is exactly what this PR is, but not manual. It is actually the way NPM describes the publishing cycle itself. And it is weird that it isn't adopted in this project.

**Comment by jacodg** [comment]
Ok, so we need to change https://github.com/wearefrank/ladybug?tab=readme-ov-file#prepare-for-next-cycle I think? Can you make a PR on the README? :)

**Comment by jacodg** [comment]
Thanks!

**Pull request merged**
